### ISSUE TITLE
Error building veeamsnap

### ISSUE THREAD

**Issue by schulh** [CodeImp/arch_packages#2]
When I'm trying to build veeamsnap, I get the following error message:
```bash
==> dkms install veeamsnap/1.0.1.364 -k 4.13.8-1-hardened
Error! Bad return status for module build on kernel: 4.13.8-1-hardened (x86_64)
Consult /var/lib/dkms/veeamsnap/1.0.1.364/build/make.log for more information.
==> dkms install veeamsnap/1.0.1.364 -k 4.13.7-1-ARCH
Error! Bad return status for module build on kernel: 4.13.7-1-ARCH (x86_64)
Consult /var/lib/dkms/veeamsnap/1.0.1.364/build/make.log for more information.
(2/2) Arming ConditionNeedsUpdate..
```

Output of the log:
```bash
DKMS make.log for veeamsnap-1.0.1.364 for kernel 4.13.7-1-ARCH (x86_64)
Fri 20 Oct 19:32:36 CEST 2017
make: Entering directory '/usr/lib/modules/4.13.7-1-ARCH/build'
  AR      /var/lib/dkms/veeamsnap/1.0.1.364/build/built-in.o
  CC [M]  /var/lib/dkms/veeamsnap/1.0.1.364/build/mem_alloc.o
  CC [M]  /var/lib/dkms/veeamsnap/1.0.1.364/build/sparse_array_1lv.o
  CC [M]  /var/lib/dkms/veeamsnap/1.0.1.364/build/sparse_bitmap.o
  CC [M]  /var/lib/dkms/veeamsnap/1.0.1.364/build/container.o
/var/lib/dkms/veeamsnap/1.0.1.364/build/mem_alloc.c: In function ‘dbg_kmalloc_huge’:
/var/lib/dkms/veeamsnap/1.0.1.364/build/mem_alloc.c:138:55: error: ‘__GFP_REPEAT’ undeclared (first use in this function); did you mean ‘__GFP_RECLAIM’?
   ptr = dbg_kmalloc( max_size, flags | __GFP_NOWARN | __GFP_REPEAT);
                                                       ^~~~~~~~~~~~
                                                       __GFP_RECLAIM
/var/lib/dkms/veeamsnap/1.0.1.364/build/mem_alloc.c:138:55: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [scripts/Makefile.build:302: /var/lib/dkms/veeamsnap/1.0.1.364/build/mem_alloc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1512: _module_/var/lib/dkms/veeamsnap/1.0.1.364/build] Error 2
make: Leaving directory '/usr/lib/modules/4.13.7-1-ARCH/build'
```
I think the problem is related to veeamsnap because it only supports kernels till version 4.10. Any suggestions?

**Comment by schumischumi** [comment]
same here. seams the support can fix it if one opens a case https://forums.veeam.com/veeam-agent-for-linux-f41/opensuse-tumbleweed-kernel-4-13-1-dkms-error-building-t45585.html

**Comment by schulh** [comment]
Thanks I will try that

**Comment by CodeImp** [comment]
2.0.0.400 support kernel 4.14.
